server:
  port: 8083

spring:
  application:
    name: ai-service
  data:
    mongodb:
      uri: mongodb+srv://shivam200020:Gurpreet%402000@cluster0.g2u4ofu.mongodb.net/fitnessActivity?retryWrites=true&w=majority&appName=Cluster0
      database: fitnessActivity

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/